- name: Install Mysql
  yum:
    name:
      - mariadb
      - mariadb-server
    state: present

- name: Start and enable Mysql
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Create database
  shell: mysql -e "create database if not exists {{ db_name }};"

- name: Check User
  shell: mysql -e "select 1 from mysql.user where user = '{{ db_user }}';" | grep -q 1
  register: user_check
  ignore_errors: yes

- name: Create user
  shell: mysql -e "CREATE USER {{ db_user }}@localhost IDENTIFIED BY '{{ db_password }}';"
  when: user_check.rc != 0

- name: Grant Priviliges
  shell: mysql -e "GRANT ALL PRIVILEGES ON {{ db_name }}.* TO {{ db_user }}@localhost IDENTIFIED BY '{{ db_password }}';"

- name: FLUSH PRIVILEGES
  shell: mysql -e "FLUSH PRIVILEGES;"